//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageList
    {
        public int Monitor_Id { get; set; }
        public string Monitor_Name { get; set; }
        public string Url { get; set; }
        public string Monitor_Group { get; set; }
        public Nullable<bool> Downtime { get; set; }
    }
}
